[tox]
min_version = 4.0
env_list =
    py311
    py312
    py313
    py314

[testenv]
extras = test
commands =
    py314: pylint backup_tool
    py314: bandit -r backup_tool
    pytest --cov=backup_tool --cov-report=term --cov-report=xml --cov-fail-under=85 tests/
