"""Initial schema

Revision ID: ef9f78b6211b
Revises: 
Create Date: 2025-12-08 13:37:16.729775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9f78b6211b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file_path', sa.String(length=256), nullable=True),
    sa.Column('original_md5_checksum', sa.String(length=32), nullable=True),
    sa.Column('uploaded_md5_checksum', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uploaded_file_path'),
    sa.UniqueConstraint('uploaded_md5_checksum')
    )
    op.create_table('backup_entry_local_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_entry_id', sa.Integer(), nullable=True),
    sa.Column('local_file_path', sa.String(length=40960), nullable=True),
    sa.ForeignKeyConstraint(['backup_entry_id'], ['backup_entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_entry_local_file')
    op.drop_table('backup_entry')
    # ### end Alembic commands ###
