"""Add cached mtime and size columns for fast change detection

Revision ID: ff8c0e19188c
Revises: ef9f78b6211b
Create Date: 2025-12-08 16:27:38.192451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8c0e19188c'
down_revision: Union[str, None] = 'ef9f78b6211b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_entry_local_file', sa.Column('cached_mtime', sa.Float(), nullable=True))
    op.add_column('backup_entry_local_file', sa.Column('cached_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup_entry_local_file', 'cached_size')
    op.drop_column('backup_entry_local_file', 'cached_mtime')
    # ### end Alembic commands ###
